//! zsx-node: N-API cdylib binding a single-process ZSX session to Node.js.
//!
//! Exposes one class, `NativeZsxSession`, over the canonical in-process
//! [`zsx_core::ZsxSession`]: the constructor builds one real full session
//! (executor thread, aggregate connector, confined host) with the three
//! domain adapters registered — the same composition the `zsx exec` binary
//! uses.
//!
//! - `execute(plan, timeoutMs, signal?)` assigns a bounded per-generation
//!   request id and returns an `AsyncTask` (a Promise); the blocking plan
//!   runs on the libuv threadpool and resolves to the canonical JSON
//!   envelope. An `AbortSignal` cancels that one request.
//! - `status()`, `reconcile()`, `shutdown()` are control-plane wrappers;
//!   `shutdown` only stops the in-process worker thread.
//!
//! The addon never spawns a process, never opens a socket, and never speaks
//! NDJSON: everything below is the zsx-core in-process path, which
//! guarantees zero child processes.
//!
//! Panic containment is explicit: every libuv worker entry point
//! (`Task::compute`) is wrapped in `catch_unwind(AssertUnwindSafe)`, so a
//! backend panic becomes a typed `internal_panic` envelope instead of
//! unwinding across the FFI boundary.
//!
//! Hand-written code in this crate contains no `unsafe`; the `unsafe` blocks
//! that exist are generated by `napi-derive` and by the `napi` runtime glue.

mod core;
mod envelope;
mod error;
mod session;
mod tasks;
