[package]
name = "zero-kernel-node"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "N-API binding for daemonless in-process ZeroKernel"
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]
name = "zero_kernel_node"

[dependencies]
napi = { workspace = true, features = ["serde-json", "napi6"] }
napi-derive = { workspace = true }
parking_lot = { workspace = true }
serde_json.workspace = true
zero-abi = { workspace = true }
zero-kernel = { workspace = true }
zero-store = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }

[lints]
workspace = true
