[package]
name = "graphzero-scip"
version.workspace = true
edition.workspace = true
license.workspace = true
autotests = false

[dependencies]
anyhow = { workspace = true }
graphzero-extract = { workspace = true }
graphzero-store = { workspace = true }
protobuf = "3.7"
scip = "0.8.1"
sha2 = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }


[lints]
workspace = true
