[package]
name = "graphzero-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_json = "1"

[dependencies.graphzero-store]
path = "../../crates/graphzero/graphzero-store"

[dependencies.graphzero-pack]
path = "../../crates/graphzero/graphzero-pack"

[dependencies.graphzero-scip]
path = "../../crates/graphzero/graphzero-scip"

[[bin]]
name = "delta_codec"
path = "fuzz_targets/delta_codec.rs"
test = false
doc = false

[[bin]]
name = "pack_sign"
path = "fuzz_targets/pack_sign.rs"
test = false
doc = false

[[bin]]
name = "scip_parse"
path = "fuzz_targets/scip_parse.rs"
test = false
doc = false

[workspace]

[profile.release]
debug = 1
