[package]
name = "graphzero-test-support"
version.workspace = true
edition.workspace = true
license.workspace = true
autotests = false
publish = false

[dependencies]
ah-ah-ah = { workspace = true }
graphzero-engine = { workspace = true }
graphzero-reserve = { workspace = true }
graphzero-store = { workspace = true, features = ["tokenzero"] }
git2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tiktoken-rs = { workspace = true }


[lints]
workspace = true
