#!/usr/bin/env python3
"""Measure the tracked implementation-line ownership across ZeroStack.

The measurement is deliberately provenance-first.  It reads only the committed
``HEAD`` tree of each named repository, extracts it to an isolated directory,
and asks ``tokei`` for code-line counts.  Working-tree files, ignored files,
prose, data, generated output, vendor trees, fixture trees, and dead code are excluded; same-repository duplicate copies are counted once; cross-repository exact duplicates remain in the denominator but never improve the hub numerator.

The checked-in ownership inventory is a reviewed classification of every
tracked file in an allowed implementation language.  It is not deletion
authority.  A changed or added implementation path requires an inventory
update before the gate can be used as release evidence.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

SCHEMA = "zerostack.loc-majority.v1"
INVENTORY_SCHEMA = "zerostack.loc-ownership.v1"
THRESHOLD = 0.50
REPOSITORIES = ("zerostack", "fszero", "graphzero", "tokenzero")

# These are the exact language families accepted by the gate.  Header variants
# are normalized into C/C++; BASH is normalized into Shell.  No other tokei
# language can enter the denominator.
LANGUAGE_BY_EXTENSION: dict[str, str] = {
    ".rs": "Rust",
    ".py": "Python",
    ".pyw": "Python",
    ".pyi": "Python",
    ".ts": "TypeScript",
    ".mts": "TypeScript",
    ".cts": "TypeScript",
    ".tsx": "TypeScript",
    ".js": "JavaScript",
    ".mjs": "JavaScript",
    ".cjs": "JavaScript",
    ".jsx": "JavaScript",
    ".c": "C",
    ".h": "C",
    ".cc": "C++",
    ".cpp": "C++",
    ".cxx": "C++",
    ".c++": "C++",
    ".hh": "C++",
    ".hpp": "C++",
    ".hxx": "C++",
    ".inl": "C++",
    ".ipp": "C++",
    ".sh": "Shell",
    ".bash": "Shell",
    ".ksh": "Shell",
    ".ps1": "PowerShell",
    ".psm1": "PowerShell",
    ".psd1": "PowerShell",
    ".zsh": "Zsh",
    ".rb": "Ruby",
    ".go": "Go",
    ".swift": "Swift",
}
LANGUAGES = tuple(dict.fromkeys(LANGUAGE_BY_EXTENSION.values()))

# A path in any of these trees is not implementation ownership.  In
# particular, fixture source is excluded so adding a large test corpus cannot
# manufacture a majority.  Tests, benches, scripts, and examples remain in.
EXCLUDED_SEGMENTS = frozenset(
    {
        ".git",
        "archive",
        "build",
        "coverage",
        "dead",
        "dist",
        "fixture",
        "fixtures",
        "generated",
        "node_modules",
        "target",
        "testdata",
        "vendor",
    }
)
GENERATED_MARKER_RE = re.compile(
    r"(?im)^\s*(?://|#|/\*|\*)\s*(?:@generated|code generated|do not edit:? generated|generated by)\b"
)
CLASSIFICATIONS = frozenset(
    {"domain-local", "thin-adapter", "shared-candidate", "excluded"}
)

# A conservative, path-reviewed map.  A candidate means "a likely reusable
# substrate target", not "move this file now".  Domain algorithms stay local
# unless a path has an explicit shared-substrate signal.
SHARED_RULES: tuple[tuple[str, tuple[str, ...], str], ...] = (
    ("raw-worker", ("raw_worker", "raw-worker"), "zero-abi"),
    ("operation-abi", ("operation_abi", "operation-abi"), "zero-abi"),
    ("telemetry", ("telemetry",), "zero-abi"),
    ("capability", ("capability",), "zero-abi"),
    (
        "zeroref",
        ("zeroref", "ref_index", "ref_resolver"),
        "zero-ref",
    ),
    (
        "store-cas",
        (
            "/cas.rs",
            "/cas.py",
            "/shared_cas.rs",
            "/embedded_store.rs",
            "/segment_store.rs",
            "/zerostack_store.rs",
            "/store_root.rs",
            "/fs_replace.rs",
            "/journal.rs",
            "/journal_",
            "/durable_journal.rs",
            "/store_migration.rs",
            "/store_pack.rs",
            "/store_schema_version.rs",
        ),
        "zero-store",
    ),
    ("machine-permit", ("permit",), "zerostack-machine-permit"),
    (
        "codemode-host",
        ("codemode", "quickjs", "mcp_protocol", "mcp_rpc", "mcp_frame", "jsonrpc", "fastmcp"),
        "zero-codemode",
    ),
    (
        "session-discovery",
        ("/session.rs", "/session_persist.rs", "/discovery.rs", "/packaging"),
        "zero-codemode",
    ),
    (
        "surface-protocol",
        ("/surface_handshake.rs", "/mcp_protocol/", "/mcp_rpc.rs", "/mcp_frame.rs", "/surface.rs"),
        "zero-codemode",
    ),
)
THIN_ADAPTER_RULE = "surface-entrypoint"
DOMAIN_RULE = "engine-domain-default"
EXCLUDED_RULE = "excluded-path-or-generated"


class GateError(ValueError):
    """A malformed provenance, inventory, or measurement input."""


@dataclass(frozen=True)
class Repo:
    id: str
    root: Path


@dataclass(frozen=True)
class Source:
    repo: str
    path: str
    language: str
    content: bytes
    code_lines: int
    digest: str
    path_reason: str | None

    @property
    def key(self) -> tuple[str, str]:
        return self.repo, self.path


@dataclass(frozen=True)
class Classification:
    kind: str
    rule: str
    hub_target: str | None
    justification: str


def _run(command: Sequence[str], *, cwd: Path | None = None, input_bytes: bytes | None = None) -> bytes:
    try:
        result = subprocess.run(
            list(command),
            cwd=cwd,
            input=input_bytes,
            capture_output=True,
            check=True,
            timeout=120,
        )
    except (OSError, subprocess.SubprocessError) as error:
        raise GateError(f"command failed: {' '.join(command)}: {error}") from error
    return result.stdout


def _git(root: Path, *args: str, input_bytes: bytes | None = None) -> bytes:
    if not root.is_dir():
        raise GateError(f"missing repository root: {root}")
    return _run(["git", "-C", str(root), *args], input_bytes=input_bytes)


def git_head(root: Path) -> str:
    head = _git(root, "rev-parse", "--verify", "HEAD").decode().strip()
    if not re.fullmatch(r"[0-9a-f]{40}", head):
        raise GateError(f"{root}: HEAD is not a full commit digest: {head!r}")
    return head


def tracked_paths(root: Path) -> list[str]:
    raw = _git(root, "ls-tree", "-r", "--name-only", "-z", "HEAD")
    paths = [item.decode("utf-8", "surrogateescape") for item in raw.split(b"\0") if item]
    if paths != sorted(paths):
        paths.sort()
    return paths


def git_blob(root: Path, path: str) -> bytes:
    return _git(root, "show", f"HEAD:{path}")


def language_for(path: str, content: bytes | None = None) -> str | None:
    suffix = Path(path).suffix.lower()
    language = LANGUAGE_BY_EXTENSION.get(suffix)
    if language is not None:
        return language
    # A tracked extensionless executable with a Python shebang is still
    # Python implementation, but no arbitrary text file enters the gate.
    if content is not None and suffix == "":
        first_line = content.splitlines()[:1]
        if first_line and first_line[0].startswith(b"#!") and b"python" in first_line[0].lower():
            return "Python"
    return None


def _path_reason(path: str, content: bytes) -> str | None:
    parts = {part.lower() for part in Path(path).parts}
    excluded = sorted(parts & EXCLUDED_SEGMENTS)
    if excluded:
        return "excluded path segment(s): " + ", ".join(excluded)
    stem = Path(path).stem.lower()
    lowered_path = path.lower()
    if "fixture" in lowered_path and any(marker in lowered_path for marker in ("padding", "padded")):
        return "fixture-padding source is excluded from LOC majority"
    if stem.startswith("generated") or stem.endswith("_generated"):
        return "generated filename"
    if stem.startswith("dead") or stem.endswith("_dead"):
        return "dead-code filename"
    prefix = content[:4096].decode("utf-8", "ignore")
    marker = GENERATED_MARKER_RE.search(prefix)
    if marker:
        return f"generated marker: {marker.group(0).strip()}"
    return None


def _canonical_hub_target(path: str) -> str:
    parts = Path(path).parts
    if len(parts) >= 2 and parts[0] == "crates":
        return parts[1]
    if path.startswith("tests/") or path.startswith("scripts/"):
        return "zero-testkit"
    return "zero-codemode"


def _normalized_path(path: str) -> str:
    return "/" + path.replace("\\", "/") + "/"


def classify_path(repo: str, path: str, content: bytes = b"") -> Classification:
    reason = _path_reason(path, content)
    if reason:
        return Classification("excluded", EXCLUDED_RULE, None, reason)
    if repo == "zerostack":
        target = _canonical_hub_target(path)
        return Classification(
            "shared-candidate",
            "hub-owned-substrate",
            target,
            f"hub implementation already owned by {target}",
        )
    normalized = _normalized_path(path).lower()
    name = Path(path).name.lower()
    # Entrypoints are adapters even when their parent package contains generic
    # implementation.  This rule intentionally runs before shared candidates.
    if (
        name == "main.rs"
        and any(token in normalized for token in ("-codemode/", "-mcp/", "-mcp-compat/"))
    ) or (
        "/src/bin/" in normalized
        and any(token in name for token in ("codemode", "mcp", "raw_worker", "raw-worker"))
    ) or "/src/surfaces/" in normalized:
        return Classification(
            "thin-adapter",
            THIN_ADAPTER_RULE,
            "zero-codemode",
            "surface entrypoint retains engine dispatch only",
        )
    for rule, needles, target in SHARED_RULES:
        if any(needle in normalized for needle in needles):
            return Classification(
                "shared-candidate",
                rule,
                target,
                f"path matches reviewed reusable-substrate rule {rule}",
            )
    return Classification(
        "domain-local",
        DOMAIN_RULE,
        None,
        f"{repo} domain implementation has no reviewed shared-substrate signal",
    )


def _tokei_version() -> str:
    try:
        result = subprocess.run(["tokei", "--version"], capture_output=True, text=True, check=True, timeout=30)
    except (OSError, subprocess.SubprocessError) as error:
        raise GateError(f"tokei is required: {error}") from error
    return result.stdout.strip()


def _tokei_counts(root: Path, paths: Iterable[str]) -> dict[str, int]:
    """Count tracked archive files by canonical language with tokei."""
    try:
        result = subprocess.run(
            [
                "tokei",
                "--output",
                "json",
                "--files",
                "--no-ignore",
                "--no-ignore-dot",
                "--no-ignore-vcs",
                "--no-ignore-parent",
                "--hidden",
                str(root),
            ],
            capture_output=True,
            text=True,
            check=True,
            timeout=120,
        )
    except (OSError, subprocess.SubprocessError) as error:
        raise GateError(f"tokei failed: {error}") from error
    try:
        report = json.loads(result.stdout)
    except json.JSONDecodeError as error:
        raise GateError(f"tokei returned invalid JSON: {error}") from error
    wanted = set(paths)
    counts: dict[str, int] = {}
    language_aliases = {
        "C Header": "C",
        "C++ Header": "C++",
        "BASH": "Shell",
        "C Shell": "Shell",
        "Korn shell": "Shell",
    }
    for tokei_language, details in report.items():
        canonical = language_aliases.get(tokei_language, tokei_language)
        if canonical not in LANGUAGES:
            continue
        for item in details.get("reports", []):
            absolute = Path(item["name"])
            try:
                relative = absolute.relative_to(root).as_posix()
            except ValueError as error:
                raise GateError(f"tokei reported a path outside archive: {absolute}") from error
            if relative in wanted:
                counts[relative] = item["stats"]["code"]
    missing = sorted(wanted - set(counts))
    if missing:
        raise GateError(f"tokei did not classify allowed tracked files: {missing[:5]}")
    return counts


def _materialize_sources(destination: Path, blobs: Mapping[str, bytes]) -> None:
    """Materialize only HEAD blobs, turning links into inert source bytes."""
    for path, content in blobs.items():
        target = destination / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)


def collect_sources(repo: Repo) -> tuple[str, list[Source], str]:
    head = git_head(repo.root)
    paths = tracked_paths(repo.root)
    blobs = {path: git_blob(repo.root, path) for path in paths}
    allowed = [path for path in paths if language_for(path, blobs[path])]
    with tempfile.TemporaryDirectory(prefix=f"loc-{repo.id}-") as temporary:
        archive_root = Path(temporary)
        _materialize_sources(archive_root, {path: blobs[path] for path in allowed})
        counts = _tokei_counts(archive_root, allowed)
    sources = [
        Source(
            repo=repo.id,
            path=path,
            language=language_for(path, blobs[path]) or "",
            content=blobs[path],
            code_lines=counts[path],
            digest=hashlib.sha256(blobs[path]).hexdigest(),
            path_reason=_path_reason(path, blobs[path]),
        )
        for path in allowed
    ]
    return head, sources, _tokei_version()


def _inventory_key(repo: str, path: str) -> str:
    return f"{repo}:{path}"


def _inventory_classifications(
    repos: Sequence[Repo],
) -> dict[tuple[str, str], Classification]:
    """Return the deterministic reviewed classification for every source."""
    sources: list[tuple[str, str, bytes, str | None]] = []
    for repo in repos:
        for path in tracked_paths(repo.root):
            content = git_blob(repo.root, path)
            if language_for(path, content):
                sources.append((repo.id, path, content, _path_reason(path, content)))
    duplicate_of, cross_repo_groups = _duplicate_canonicals(
        [
            Source(
                repo=repo,
                path=path,
                language=language_for(path, content) or "",
                content=content,
                code_lines=0,
                digest=hashlib.sha256(content).hexdigest(),
                path_reason=path_reason,
            )
            for repo, path, content, path_reason in sources
        ]
    )
    cross_repo_members = {
        key: group for group in cross_repo_groups for key in group
    }
    result: dict[tuple[str, str], Classification] = {}
    for repo, path, content, path_reason in sources:
        key = (repo, path)
        if path_reason is not None:
            result[key] = Classification("excluded", EXCLUDED_RULE, None, path_reason)
        elif key in cross_repo_members:
            members = ", ".join(
                f"{member_repo}:{member_path}"
                for member_repo, member_path in cross_repo_members[key]
            )
            result[key] = Classification(
                "excluded",
                "cross-repo-duplicate",
                None,
                f"exact-byte duplicate across repositories ({members}); all copies remain in the denominator, are excluded from the hub numerator, and fail the gate",
            )
        elif key in duplicate_of:
            canonical = duplicate_of[key]
            result[key] = Classification(
                "excluded",
                "duplicate-content",
                None,
                f"exact-byte duplicate of {canonical[0]}:{canonical[1]}; canonical path wins",
            )
        else:
            result[key] = classify_path(repo, path, content)
    return result


def build_inventory(repos: Sequence[Repo]) -> dict[str, Any]:
    entries: list[dict[str, Any]] = []
    heads: dict[str, str] = {}
    classifications = _inventory_classifications(repos)
    for repo in repos:
        heads[repo.id] = git_head(repo.root)
        for path in tracked_paths(repo.root):
            content = git_blob(repo.root, path)
            language = language_for(path, content)
            if not language:
                continue
            classification = classifications[(repo.id, path)]
            item: dict[str, Any] = {
                "repo": repo.id,
                "path": path,
                "language": language,
                "classification": classification.kind,
                "rule": classification.rule,
                "justification": classification.justification,
            }
            if classification.hub_target is not None:
                item["hub_target"] = classification.hub_target
            entries.append(item)
    entries.sort(key=lambda item: (REPOSITORIES.index(item["repo"]), item["path"]))
    return {
        "schema": INVENTORY_SCHEMA,
        "version": 1,
        "generated_from_heads": heads,
        "languages": list(LANGUAGES),
        "classification_values": sorted(CLASSIFICATIONS),
        "rules": {
            "included_scopes": ["production", "tests", "benches", "scripts", "examples"],
            "excluded_segments": sorted(EXCLUDED_SEGMENTS),
            "excluded_path_rules": ["fixture-tree", "fixture-padding", "generated-marker", "generated-filename", "dead-code-filename"],
            "duplicate_policy": "cross-repository exact duplicates remain in the denominator, contribute no duplicated hub LOC, and fail the gate; same-repository duplicates count once",
            "domain_policy": "engine algorithms remain domain-local unless an explicit rule marks a candidate",
        },
        "files": entries,
    }


def load_inventory(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise GateError(f"cannot read ownership inventory {path}: {error}") from error
    if not isinstance(value, dict) or value.get("schema") != INVENTORY_SCHEMA:
        raise GateError(f"{path}: wrong ownership inventory schema")
    if not isinstance(value.get("files"), list):
        raise GateError(f"{path}: files must be an array")
    return value


def validate_inventory(inventory: Mapping[str, Any], repos: Sequence[Repo]) -> list[str]:
    errors: list[str] = []
    entries = inventory.get("files")
    if not isinstance(entries, list):
        return ["inventory files must be an array"]
    seen: dict[str, int] = Counter()
    actual: dict[str, tuple[Repo, str, bytes]] = {}
    reviewed = _inventory_classifications(repos)
    expected_heads = {repo.id: git_head(repo.root) for repo in repos}
    if inventory.get("generated_from_heads") != expected_heads:
        errors.append("inventory generated_from_heads does not match current repository HEADs")
    for repo in repos:
        for path in tracked_paths(repo.root):
            content = git_blob(repo.root, path)
            if language_for(path, content):
                actual[_inventory_key(repo.id, path)] = (repo, path, content)
    for index, item in enumerate(entries):
        if not isinstance(item, dict):
            errors.append(f"files[{index}] is not an object")
            continue
        repo = item.get("repo")
        path = item.get("path")
        key = _inventory_key(repo, path) if isinstance(repo, str) and isinstance(path, str) else ""
        seen[key] += 1
        if key not in actual:
            errors.append(f"files[{index}] is not a current tracked allowed-language file: {key!r}")
            continue
        expected_language = language_for(path, actual[key][2])
        if item.get("language") != expected_language:
            errors.append(f"{key}: language mismatch")
        classification = reviewed[(repo, path)]
        if item.get("classification") != classification.kind:
            errors.append(
                f"{key}: classification {item.get('classification')!r} != reviewed {classification.kind!r}"
            )
        if item.get("rule") != classification.rule:
            errors.append(f"{key}: rule mismatch")
        if not isinstance(item.get("justification"), str) or not item["justification"].strip():
            errors.append(f"{key}: missing classification justification")
        if classification.hub_target is None:
            if "hub_target" in item:
                errors.append(f"{key}: domain/excluded classification must not have hub_target")
        elif item.get("hub_target") != classification.hub_target:
            errors.append(f"{key}: hub_target mismatch")
    for key in sorted(set(seen)):
        if seen[key] > 1:
            errors.append(f"{key}: multiply classified ({seen[key]} entries)")
    expected = set(actual)
    observed = set(seen)
    for key in sorted(expected - observed):
        errors.append(f"{key}: uncovered tracked allowed-language file")
    for key in sorted(observed - expected):
        errors.append(f"{key}: inventory entry is not in current source tree")
    return errors


def _duplicate_canonicals(
    sources: Sequence[Source],
) -> tuple[dict[tuple[str, str], tuple[str, str]], list[tuple[tuple[str, str], ...]]]:
    """Separate same-repo deduplication from cross-repo anti-gaming violations."""
    groups: defaultdict[bytes, list[Source]] = defaultdict(list)
    for source in sources:
        if source.path_reason is None:
            groups[source.content].append(source)
    duplicates: dict[tuple[str, str], tuple[str, str]] = {}
    cross_repo_groups: list[tuple[tuple[str, str], ...]] = []
    order = {repo: index for index, repo in enumerate(REPOSITORIES)}
    for group in groups.values():
        if len(group) < 2:
            continue
        ordered = sorted(group, key=lambda source: (order.get(source.repo, 99), source.path))
        keys = tuple(source.key for source in ordered)
        if len({source.repo for source in group}) > 1:
            # Keep all copies in the denominator.  The hub copy is never part
            # of the numerator, and the group is a loud gate violation.
            cross_repo_groups.append(keys)
            continue
        canonical = ordered[0]
        for source in group:
            if source.key != canonical.key:
                duplicates[source.key] = canonical.key
    return duplicates, cross_repo_groups


def _threshold(numerator: int, denominator: int, threshold: float = THRESHOLD) -> bool:
    if denominator <= 0:
        raise GateError("implementation denominator must be positive")
    # Avoid a float boundary accepting equality.  The public threshold is 1/2.
    if threshold != THRESHOLD:
        return numerator / denominator > threshold
    return numerator * 2 > denominator


def measure(repos: Sequence[Repo], inventory: Mapping[str, Any]) -> dict[str, Any]:
    ids = tuple(repo.id for repo in repos)
    if ids != REPOSITORIES:
        raise GateError(f"denominator must contain exactly {REPOSITORIES}, got {ids}")
    if len({repo.id for repo in repos}) != len(repos):
        raise GateError("repository IDs must be unique")
    inventory_errors = validate_inventory(inventory, repos)
    if inventory_errors:
        raise GateError("ownership inventory invalid:\n" + "\n".join(f"  - {error}" for error in inventory_errors))
    all_sources: list[Source] = []
    heads: dict[str, str] = {}
    tokei_versions: set[str] = set()
    for repo in repos:
        head, sources, version = collect_sources(repo)
        heads[repo.id] = head
        tokei_versions.add(version)
        all_sources.extend(sources)
    duplicate_of, cross_repo_groups = _duplicate_canonicals(all_sources)
    cross_repo_members = {key for group in cross_repo_groups for key in group}
    excluded: dict[tuple[str, str], str] = {}
    for source in all_sources:
        if source.path_reason:
            excluded[source.key] = source.path_reason
        elif source.key in duplicate_of:
            excluded[source.key] = f"duplicate content of {duplicate_of[source.key][0]}:{duplicate_of[source.key][1]}"
    repository_rows: list[dict[str, Any]] = []
    ownership_counts: Counter[str] = Counter()
    language_totals: Counter[str] = Counter()
    for repo in repos:
        repo_sources = [source for source in all_sources if source.repo == repo.id]
        # Cross-repository duplicates remain counted here so the denominator
        # cannot shrink when a copy is added.  The hub numerator removes them
        # separately below.  Same-repository duplicates remain deduplicated.
        counted = [source for source in repo_sources if source.key not in excluded]
        repo_excluded = [source for source in repo_sources if source.key in excluded]
        cross_repo_duplicates = [source for source in repo_sources if source.key in cross_repo_members]
        by_language = Counter({language: 0 for language in LANGUAGES})
        for source in counted:
            by_language[source.language] += source.code_lines
            language_totals[source.language] += source.code_lines
            if source.key not in cross_repo_members:
                ownership_counts[next(
                    item["classification"]
                    for item in inventory["files"]
                    if item["repo"] == repo.id and item["path"] == source.path
                )] += source.code_lines
        repository_rows.append(
            {
                "id": repo.id,
                "head": heads[repo.id],
                "tracked_implementation_files": len(repo_sources),
                "counted_files": len(counted),
                "excluded_files": len(repo_excluded),
                "duplicate_files": len(cross_repo_duplicates) + sum(source.key in duplicate_of for source in repo_sources),
                "duplicate_code_lines": sum(source.code_lines for source in cross_repo_duplicates),
                "excluded_code_lines": sum(source.code_lines for source in repo_excluded),
                "implementation_loc": sum(source.code_lines for source in counted),
                "hub_numerator_loc": (
                    sum(
                        source.code_lines
                        for source in counted
                        if repo.id == "zerostack" and source.key not in cross_repo_members
                    )
                    if repo.id == "zerostack"
                    else 0
                ),
                "by_language": {language: by_language[language] for language in LANGUAGES if by_language[language]},
                "excluded_reasons": dict(sorted(Counter(excluded[source.key] for source in repo_excluded).items())),
                "duplicate_reasons": {
                    "cross-repo-exact-duplicate": len(cross_repo_duplicates),
                    "same-repo-exact-duplicate": sum(source.key in duplicate_of for source in repo_sources),
                },
            }
        )
    denominator = sum(row["implementation_loc"] for row in repository_rows)
    hub_loc = sum(
        source.code_lines
        for source in all_sources
        if source.repo == "zerostack"
        and source.key not in excluded
        and source.key not in cross_repo_members
    )
    threshold_pass = _threshold(hub_loc, denominator)
    passing = threshold_pass and not cross_repo_groups
    transfer = max(0, denominator // 2 + 1 - hub_loc)
    new_hub = max(0, denominator - 2 * hub_loc + 1)
    source_by_key = {source.key: source for source in all_sources}
    duplicate_violations = [
        {
            "digest": source_by_key[group[0]].digest,
            "files": [
                {
                    "repo": repo,
                    "path": path,
                    "code_lines": source_by_key[(repo, path)].code_lines,
                }
                for repo, path in group
            ],
            "code_lines": sum(source_by_key[key].code_lines for key in group),
            "message": "cross-repository exact duplicate; all copies remain denominator-visible, hub copies do not contribute to hub numerator",
        }
        for group in cross_repo_groups
    ]
    candidates = [
        {
            "repo": item["repo"],
            "path": item["path"],
            "hub_target": item.get("hub_target"),
            "rule": item["rule"],
        }
        for item in inventory["files"]
        if item.get("classification") in {"shared-candidate", "thin-adapter"}
        and item.get("repo") != "zerostack"
    ]
    return {
        "schema": SCHEMA,
        "version": 1,
        "source_heads": heads,
        "tool": {"name": "tokei", "versions": sorted(tokei_versions)},
        "languages": list(LANGUAGES),
        "repositories": repository_rows,
        "denominator": {
            "repository_ids": list(REPOSITORIES),
            "implementation_loc": denominator,
            "formula": "sum(repositories[*].implementation_loc)",
        },
        "hub": {"repository_id": "zerostack", "implementation_loc": hub_loc},
        "hub_share": hub_loc / denominator,
        "threshold": {"operator": ">", "value": THRESHOLD},
        "pass": passing,
        "violations": {
            "cross_repo_exact_duplicates": duplicate_violations,
            "count": len(duplicate_violations),
        },
        "migration": {
            "minimum_denominator_preserving_transfer_lines": transfer,
            "minimum_new_hub_lines_if_denominator_grows": new_hub,
            "note": "transfer is integer LOC moved from engines to the hub while preserving denominator",
        },
        "ownership_line_totals": dict(sorted(ownership_counts.items())),
        "engine_shared_candidates": candidates,
    }


def default_repos() -> list[Repo]:
    hub = Path(__file__).resolve().parents[2]
    roots = {
        "zerostack": hub,
        "fszero": hub.parent / "FSZero",
        "graphzero": hub.parent / "GraphZero",
        "tokenzero": hub.parent / "TokenZero",
    }
    return [Repo(repo_id, roots[repo_id]) for repo_id in REPOSITORIES]


def write_inventory(path: Path, repos: Sequence[Repo]) -> None:
    value = build_inventory(repos)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=False) + "\n", encoding="utf-8")


def _tiny_repo(path: Path, files: Mapping[str, str]) -> None:
    path.mkdir(parents=True, exist_ok=True)
    _run(["git", "init", "-q", str(path)])
    for name, text in files.items():
        target = path / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
    _run(["git", "-C", str(path), "add", "--", *files])
    _run(
        [
            "git",
            "-C",
            str(path),
            "-c",
            "user.name=loc-self-test",
            "-c",
            "user.email=loc-self-test@example.invalid",
            "commit",
            "-qm",
            "fixture",
        ]
    )


def self_test() -> None:
    """Run mutation checks without touching any repository checkout."""
    with tempfile.TemporaryDirectory(prefix="loc-majority-self-test-") as temporary:
        root = Path(temporary)
        files = {
            "src/domain.rs": "fn domain() {}\nfn domain_two() {}\n",
            "src/shared.rs": "fn shared() {}\n",
            "tests/check.py": "assert True\n",
            "benches/bench.rs": "fn bench() {}\n",
            "scripts/tool.py": "print('tool')\n",
            "examples/demo.rs": "fn main() {}\n",
            "vendor/padded.rs": "fn padded() {}\n",
            "tests/fixtures/padded.rs": "fn fixture() {}\n",
            "tests/fixtures/padding.rs": "fn padding() {}\n",
            "fixtures/giant.rs": "".join(
                f"fn fixture_giant_{index}() {{}}\n" for index in range(1000)
            ),
            "src/generated.rs": "fn generated() {}\n",
        }
        repos = []
        for repo_id in REPOSITORIES:
            repo_root = root / repo_id
            if repo_id == "zerostack":
                repo_files = {
                    path: text
                    for path, text in files.items()
                    if not any(segment in path for segment in ("vendor/", "fixtures/", "generated.rs"))
                }
            else:
                repo_files = {
                    f"src/domain_{index}.rs": (
                        f"fn {repo_id}_domain_{index}() {{}}\n"
                        f"fn {repo_id}_domain_{index}_two() {{}}\n"
                    )
                    for index in range(1, 5)
                }
            _tiny_repo(repo_root, repo_files)
            repos.append(Repo(repo_id, repo_root))
        inventory = build_inventory(repos)
        baseline = measure(repos, inventory)
        assert baseline["pass"] is False
        assert baseline["denominator"]["repository_ids"] == list(REPOSITORIES)
        assert baseline["repositories"][0]["head"] == git_head(repos[0].root)
        # These non-fixture scopes remain eligible for counting.
        assert baseline["repositories"][0]["counted_files"] >= 6

        # Missing repository and omitted denominator repository must fail closed.
        try:
            measure(repos[:3], inventory)
        except GateError:
            pass
        else:
            raise AssertionError("omitted denominator repository accepted")
        try:
            measure([Repo("tokenzero", root / "missing"), *repos[1:]], inventory)
        except GateError:
            pass
        else:
            raise AssertionError("missing repository accepted")

        # Untracked-only growth cannot change a HEAD-bound result.
        (repos[0].root / "src/untracked.rs").write_text("fn untracked() {}\n", encoding="utf-8")
        assert measure(repos, inventory)["denominator"] == baseline["denominator"]

        # Commit generated/vendor/fixture-padding candidates after the baseline.
        for path in ("vendor/padded.rs", "tests/fixtures/padded.rs", "tests/fixtures/padding.rs", "fixtures/giant.rs", "src/generated.rs"):
            target = repos[0].root / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(files[path], encoding="utf-8")

        # Commit padding candidates so they are visible to the HEAD-bound scan.
        _run(["git", "-C", str(repos[0].root), "add", "--", "vendor/padded.rs", "tests/fixtures/padded.rs", "tests/fixtures/padding.rs", "fixtures/giant.rs", "src/generated.rs"])
        _run(["git", "-C", str(repos[0].root), "commit", "-qm", "padding"])
        padding_inventory = build_inventory(repos)
        padding_result = measure(repos, padding_inventory)
        # Generated/vendor/fixture paths never count, even when committed.
        reasons = padding_result["repositories"][0]["excluded_reasons"]
        assert any("vendor" in reason for reason in reasons)
        assert any("fixture" in reason for reason in reasons)
        assert any("generated filename" in reason for reason in reasons)
        assert padding_result["denominator"] == baseline["denominator"]
        assert padding_result["hub_share"] == baseline["hub_share"]

        # Copying engine/domain source into the hub is a loud violation.  The
        # duplicate remains denominator-visible, but neither copy can improve
        # the hub numerator.
        copied_hub = repos[0].root / "src/copied_engine_domain.rs"
        copied_hub.write_bytes((repos[1].root / "src/domain_1.rs").read_bytes())
        _run(["git", "-C", str(repos[0].root), "add", "src/copied_engine_domain.rs"])
        _run(["git", "-C", str(repos[0].root), "commit", "-qm", "hub-duplicate"])
        duplicate_inventory = build_inventory(repos)
        duplicate_result = measure(repos, duplicate_inventory)
        assert duplicate_result["violations"]["count"] >= 1
        assert duplicate_result["pass"] is False
        assert duplicate_result["hub"]["implementation_loc"] == padding_result["hub"]["implementation_loc"]
        assert duplicate_result["hub_share"] < padding_result["hub_share"]

        # Classification, coverage, and multiplicity mutations fail.
        bad = json.loads(json.dumps(duplicate_inventory))
        bad["files"][0]["classification"] = "domain-local"
        assert validate_inventory(bad, repos)
        bad = json.loads(json.dumps(duplicate_inventory))
        bad["files"] = bad["files"][1:]
        assert validate_inventory(bad, repos)
        bad = json.loads(json.dumps(duplicate_inventory))
        bad["files"].append(dict(bad["files"][0]))
        assert validate_inventory(bad, repos)

        # Equality is not a pass for the strict 50% gate.
        assert _threshold(50, 100) is False
        assert _threshold(51, 100) is True
    print("loc-majority self-test passed: provenance, fixture exclusion, cross-repo duplicate, inventory, and threshold mutations")


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inventory", type=Path, default=Path(__file__).parents[1] / "data/loc_ownership_v1.json")
    parser.add_argument("--write-inventory", action="store_true", help="write the reviewed inventory for current HEAD trees")
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--json", action="store_true", help="emit machine-readable measurement JSON")
    parser.add_argument("roots", nargs="*", type=Path)
    args = parser.parse_args(argv)
    try:
        if args.self_test:
            self_test()
            return 0
        repos = default_repos() if not args.roots else [Repo(repo_id, root.resolve()) for repo_id, root in zip(REPOSITORIES, args.roots, strict=False)]
        if args.roots and len(args.roots) != len(REPOSITORIES):
            raise GateError(f"expected exactly four repository roots in order {REPOSITORIES}")
        if args.write_inventory:
            write_inventory(args.inventory, repos)
            print(f"wrote ownership inventory: {args.inventory}")
            return 0
        inventory = load_inventory(args.inventory)
        result = measure(repos, inventory)
        encoded = json.dumps(result, indent=2, sort_keys=False)
        if args.json:
            print(encoded)
        else:
            print(encoded)
        return 0 if result["pass"] else 2
    except GateError as error:
        print(f"loc-majority gate: FAIL\n  - {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
